name: 01-Build and Prepare Docker Image

on:
  workflow_dispatch:  # Allows you to manually trigger this workflow from GitHub

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # Step 4: Save the Docker image to a file
      - name: Save Docker Image as a .tar file
        run: |
          docker save my-app:latest > my-app.tar

      # Step 5: Upload the Docker image as an artifact
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-image
          path: my-app.tar

      # Step 6: Print Docker commands for local testing
      - name: Print Docker Image Info and Run Command
        run: |
          echo "Docker image has been built successfully!"
          echo "To use this image locally, follow these steps:"
          echo ""
          echo "1. Download the Docker image artifact (my-app.tar) from this workflow run in GitHub Actions."
          echo "2. Load the Docker image into your local Docker:"
          echo "   docker load < my-app.tar"
          echo ""
          echo "3. Run the Docker container locally:"
          echo "   docker run -d -p 8080:80 my-app:latest"
          echo ""
